FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel AS torch-env 

RUN apt-get update && \
    apt-get install -y wget

RUN wget https://aihwkit-gpu-demo.s3.us-east.cloud-object-storage.appdomain.cloud/aihwkit-0.9.2+cuda121-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install aihwkit-0.9.2+cuda121-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install wandb gymnasium==0.28.1 tyro tensorboard swanlab
