FROM python:3.7.3 AS python-env
# FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel AS memoristor-env 

ENV SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL True

# RUN rm /etc/apt/sources.list.d/cuda.list
# RUN rm /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && \
    apt-get install -y openssh-server libopenmpi-dev openmpi-bin openmpi-common openmpi-doc git
#     apt-get upgrade -y && \
#     apt-get install -y git

RUN --mount=type=cache,target=/root/.cache/pip \
     python3 -m pip install mpi4py wandb gymnasium numpy==1.21.0 sklearn 

RUN --mount=type=cache,target=/root/.cache/pip \
     python3 -m pip install torch==1.7.0+cpu torchvision==0.8.0+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
