FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel AS torch-env 
RUN python --version

# RUN --mount=type=cache,target=/root/.cache/pip \
#     python3 -m pip install git+https://github.com/IBM/aihwkit.git

# RUN apt-get update && \
#    apt-get upgrade -y && \
#    apt-get install -y wget

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install cmake>=3.18 scikit-build>=0.11.1 scikit-learn pybind11>=2.6.2 scipy requests>=2.25,<3 numpy>=1.22,<2 protobuf>=4.21.6 tqdm mypy==0.991

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install wandb gymnasium==0.28.1 tyro

RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install aihwkit

# RUN wget https://aihwkit-gpu-demo.s3.us-east.cloud-object-storage.appdomain.cloud/aihwkit-0.9.2+cuda121-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

# RUN --mount=type=cache,target=/root/.cache/pip \
#     python3 -m pip install aihwkit-0.9.2+cuda121-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
